"""remove module id from lessons

Revision ID: 1f993633fb22
Revises: 87aab9a25b18
Create Date: 2026-09-09 00:59:58.611509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f993633fb22'
down_revision: Union[str, Sequence[str], None] = '87aab9a25b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_constraint(op.f('lessons_module_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lessons_module_id_fkey'), 'lessons', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    # ### end Alembic commands ###
