"""add lesson videos and video progress

Revision ID: 34eab7ef0117
Revises: faed4e9ece6f
Create Date: 2026-09-08 23:50:32.380305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34eab7ef0117'
down_revision: Union[str, Sequence[str], None] = 'faed4e9ece6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_videos_id'), 'lesson_videos', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_videos_lesson_id'), 'lesson_videos', ['lesson_id'], unique=False)
    op.create_table('lesson_video_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['lesson_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_progress')
    )
    op.create_index(op.f('ix_lesson_video_progress_id'), 'lesson_video_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_video_progress_user_id'), 'lesson_video_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_lesson_video_progress_video_id'), 'lesson_video_progress', ['video_id'], unique=False)
    op.alter_column('courses', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('lessons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_column('lessons', 'video_url')
    op.drop_column('lessons', 'is_free')
    op.drop_column('lessons', 'duration')
    op.drop_column('lessons', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=False)
    op.alter_column('lessons', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('lessons', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('courses', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_lesson_video_progress_video_id'), table_name='lesson_video_progress')
    op.drop_index(op.f('ix_lesson_video_progress_user_id'), table_name='lesson_video_progress')
    op.drop_index(op.f('ix_lesson_video_progress_id'), table_name='lesson_video_progress')
    op.drop_table('lesson_video_progress')
    op.drop_index(op.f('ix_lesson_videos_lesson_id'), table_name='lesson_videos')
    op.drop_index(op.f('ix_lesson_videos_id'), table_name='lesson_videos')
    op.drop_table('lesson_videos')
    # ### end Alembic commands ###
