"""create lesson videos and progress

Revision ID: 6ed96e7bc5f1
Revises: 34eab7ef0117
Create Date: 2026-09-09 00:46:08.030239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed96e7bc5f1'
down_revision: Union[str, Sequence[str], None] = '34eab7ef0117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_column('lessons', 'course_id')
    # ### end Alembic commands ###
