"""add module id to lessons

Revision ID: 87aab9a25b18
Revises: 6ed96e7bc5f1
Create Date: 2026-09-09 00:57:21.858482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aab9a25b18'
down_revision: Union[str, Sequence[str], None] = '6ed96e7bc5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
