"""create enrollments table

Revision ID: d9179f932c6c
Revises: fc0d780fa636
Create Date: 2026-08-13 20:50:26.397296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d9179f932c6c"
down_revision: Union[str, Sequence[str], None] = "fc0d780fa636"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "CANCELLED",
                "COMPLETED",
                name="enrollmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("enrolled_at", sa.DateTime(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id",
            "course_id",
            name="uq_enrollment_student_course",
        ),
    )

    op.create_index(
        op.f("ix_enrollments_course_id"),
        "enrollments",
        ["course_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_enrollments_id"),
        "enrollments",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_enrollments_student_id"),
        "enrollments",
        ["student_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_index(op.f("ix_enrollments_student_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_course_id"), table_name="enrollments")
    op.drop_table("enrollments")
    # ### end Alembic commands ###
