"""add lesson timestamp defaults

Revision ID: e3c70f9774ec
Revises: a05e2dd1cef1
Create Date: 2026-09-09 01:03:34.088897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c70f9774ec'
down_revision: Union[str, Sequence[str], None] = 'a05e2dd1cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
