"""add user_id to lessons and lesson video

Revision ID: f9ab1d003ba9
Revises: b7a1c4d9e2f3
Create Date: 2026-09-12 11:09:26.856414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ab1d003ba9'
down_revision: Union[str, Sequence[str], None] = 'b7a1c4d9e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_videos', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lesson_videos_user_id'), 'lesson_videos', ['user_id'], unique=False)
    op.create_foreign_key(None, 'lesson_videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('lessons', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lessons_user_id'), 'lessons', ['user_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_user_id'), table_name='lessons')
    op.drop_column('lessons', 'user_id')
    op.drop_constraint(None, 'lesson_videos', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_videos_user_id'), table_name='lesson_videos')
    op.drop_column('lesson_videos', 'user_id')
    # ### end Alembic commands ###
