"""create free courses table

Revision ID: fa784267f414
Revises: 5f704f89267d
Create Date: 2026-08-06 22:08:10.578090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "fa784267f414"
down_revision: Union[str, Sequence[str], None] = "5f704f89267d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "free_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "language",
            ENUM(
                "BANGLA",
                "ENGLISH",
                name="courselanguage",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            ENUM(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="coursestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("thumbnail", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_public_id", sa.String(length=255), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_free_courses_id"),
        "free_courses",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_free_courses_slug"),
        "free_courses",
        ["slug"],
        unique=True,
    )
    op.create_index(
        op.f("ix_free_courses_title"),
        "free_courses",
        ["title"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_free_courses_title"), table_name="free_courses")
    op.drop_index(op.f("ix_free_courses_slug"), table_name="free_courses")
    op.drop_index(op.f("ix_free_courses_id"), table_name="free_courses")
    op.drop_table("free_courses")
    # ### end Alembic commands ###
