"""replace sections with modules and lessons

Revision ID: fc0d780fa636
Revises: fa784267f414
Create Date: 2026-08-12 23:32:05.449727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc0d780fa636"
down_revision: Union[str, Sequence[str], None] = "fa784267f414"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_modules_course_id"),
        "modules",
        ["course_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_modules_id"),
        "modules",
        ["id"],
        unique=False,
    )

    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_lessons_id"),
        "lessons",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_lessons_module_id"),
        "lessons",
        ["module_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_lessons_slug"),
        "lessons",
        ["slug"],
        unique=False,
    )

    op.drop_table("sections")

    op.add_column(
        "courses",
        sa.Column(
            "start_date",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "courses",
        sa.Column(
            "end_date",
            sa.DateTime(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "end_date")
    op.drop_column("courses", "start_date")
    op.create_table(
        "sections",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("sections_course_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sections_pkey")),
    )
    op.drop_index(op.f("ix_lessons_slug"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_module_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_modules_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_course_id"), table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
